version: '4.27.1'

services:
    db:
      image: postgres:16.1
      container_name: db-message
      restart: always
      volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      environment:
        POSTGRES_DB: message
        POSTGRES_USER: susaya
        POSTGRES_PASSWORD: susaya
      ports:
        - '5432:5432'
    zookeeper:
      image: confluentinc/cp-zookeeper:7.4.3
      container_name: load-balancer
      restart: always
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"

    kafka:
      image: confluentinc/cp-kafka:7.4.3
      container_name: msg-broker
      restart: always
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      ports:
        - "9092:9092"
    
    ms-discovery:
      image: ms-discovery:latest
      container_name: ms-discovery
      restart: always
      ports:
        - "8761:8761"

    ms-config-server:
      image: ms-config-server:latest
      container_name: ms-config-server
      restart: always
      ports:
        - "8888:8888"
      depends_on:
        - ms-discovery
      environment:
        EUREKA_URL: http://ms-discovery:8761/eureka/
    
    ms-batch:
      image: ms-batch:1.0.0
      container_name: ms-batch
      restart: always
      ports:
        - "8087:8087"
      depends_on:
        - ms-discovery
        - ms-config-server
        - kafka
      environment:
        EUREKA_URL: http://ms-discovery:8761/eureka/
        CONFIG_SERVER: 'http://ms-config-server:8888'
        BROKER_URL: 'msg-broker:9092'
    ms-micro1:
      image: ms-micro1:latest
      container_name: ms-micro1
      restart: always
      ports:
        - "8089:8089"
      depends_on:
        - ms-discovery
        - kafka
      environment:
        EUREKA_URL: http://ms-discovery:8761/eureka/
        BROKER_URL: 'msg-broker:9092'